package com.ironhack.products_inventory.model;

import com.ironhack.products_inventory.enums.OrderOrigin;
import com.ironhack.products_inventory.enums.OrderStatus;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.PrimaryKeyJoinColumn;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.util.List;

@NoArgsConstructor
@Entity
@PrimaryKeyJoinColumn(name = "order_id")
public class PurchaseOrder extends Orders {

    private String supplierName;

    //A CONTRUCTOR ID = null, BECAUSE IT IS AUTOGENERATED

    public PurchaseOrder(LocalDate orderDate, OrderStatus status, OrderOrigin origin, List<OrderSafe> orderSafes, String supplierName) {
        super(null, orderDate, status, origin, orderSafes);
        this.supplierName = supplierName;
    }

    @Override
    public String getDisplayId(){
        return "P" + getOrderId();
    }
}
