package com.ironhack.products_inventory.model;

import com.ironhack.products_inventory.enums.OrderOrigin;
import com.ironhack.products_inventory.enums.OrderStatus;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.PrimaryKeyJoinColumn;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.util.List;

@NoArgsConstructor
@Entity
@PrimaryKeyJoinColumn(name = "order_id")
public class SalesOrder extends Orders {

    private String customerName;
    private String customerAddress;

    //ID = null, BECAUSE IT IS AUTOGENERATED
    public SalesOrder(LocalDate orderDate, OrderStatus status, OrderOrigin origin, List<OrderSafe> orderSafes, String customerName, String customerAddress) {
        super(null, orderDate, status, origin, orderSafes);
        this.customerName = customerName;
        this.customerAddress = customerAddress;
    }

    @Override
    public String getDisplayId(){
        return "S" + getOrderId();
    }
}
