package com.ironhack.products_inventory.model;

import com.ironhack.products_inventory.enums.OrderOrigin;
import com.ironhack.products_inventory.enums.OrderStatus;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.PrimaryKeyJoinColumn;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@NoArgsConstructor
@Entity
@PrimaryKeyJoinColumn(name = "order_id")
public class SalesOrder extends Orders {

    private String customerName;
    private String customerAddress;

    //A CONTRUCTOR WITHOUT ID, BECAUSE IT IS AUTOGENERATED
    public SalesOrder(LocalDate orderDate, OrderStatus status, int quantityOrdered, Products product, String customerName, String customerAddress, OrderOrigin origin) {
        super(null, orderDate, status, quantityOrdered, origin, product);
        this.customerName = customerName;
        this.customerAddress = customerAddress;
    }

    @Override
    public String getDisplayId(){
        return "S" + getOrderId();
    }
}
